# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('platform', models.CharField(max_length=16)),
                ('score', models.FloatField(max_length=3)),
                ('genre', models.CharField(max_length=17)),
                ('editors_choice', models.CharField(max_length=1)),
            ],
        ),
    ]
